### ISSUE TITLE
bootstrap() must be an instance of SamIT\Yii2\StaticAssets\void, none returned

### ISSUE THREAD

**Issue by ItsReddi** [SAM-IT/yii2-static-assets#4]
Version 0.6.3

/var/www/html # php --version
PHP 7.0.27 (cli) (built: Jan 10 2018 03:57:49) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.27, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.0, Copyright (c) 2002-2016, by Derick Rethans

Reproduce:
1. docker run --rm --interactive --tty -v YOURAPPPATH:/app composer require sam-it/yii2-static-assets --ignore-platform-reqs
2. Run Yii in php container
![grafik](https://user-images.githubusercontent.com/3147888/39199335-822e94c2-47e9-11e8-8f98-1999012b9766.png)

Well error leads to php version. Void type is implemented in 7.1, is it possible to remove the void constraint?

**Comment by SamMousa** [comment]
I'm sorry, PHP 7.0 is EOL and I do not support it.

http://php.net/supported-versions.php

**Comment by ItsReddi** [comment]
Okay thank you, but great work! Will fork and edit then.

**Comment by SamMousa** [comment]
Okay, good luck. Let me know if you add any features or when you switch to php 7.1!

PS. Also check out yii2-phpfpm!
