### ISSUE TITLE
How to configure the AssetManager Component?

### ISSUE THREAD

**Issue by blancsys** [SAM-IT/yii2-static-assets#6]
Hello, first of all, thank you very much again for your support to understand [how to use the console command to publish the assets](https://github.com/SAM-IT/yii2-static-assets/issues/5).

So, I have successfully executed the following command:

```
$ ./yii staticAssets/asset/publish runtime/build12345
Publishing default bundle to webroot...
Creating asset path: runtime/build12345... OK
Publishing application assets... Autoloading: yii\bootstrap4\Nav
Parsing file: /home/developer/Code/horizon/vendor/kartik-v/yii2-nav-x/src/NavXBs4.phpAutoloading: yii\bootstrap4\Alert
Parsing file: /home/developer/Code/horizon/vendor/kartik-v/yii2-widget-alert/src/Bs4Alert.phpOK
Publishing vendor assets... OK
Compressing assets... OK
```

Now, my question is: how to configure the config/web.php config file to use your Assets Manager and the assets created in the previous step?

I guess that configuration should contain something like this:

```
        // Custom AssetManager
        'assetManager' => [
            'class' => \SamIT\Yii2\StaticAssets\ReadOnlyAssetManager::class,
            'assetDevelopmentMode' => false,
            // What else?
        ],
```
How can I indicate that I want to use the new "runtime/build12345" assets bundle?

Thank you very much in advance.

**Comment by SamMousa** [comment]
I think the asset manager has an asset path (I'm on a phone so can't easily check). The read only asset manager is basically a normal asset manager that doesn't copy. So it generates the path for the assets in the same way the normal asset manager does, which is by configuring the asset path.

**Comment by blancsys** [comment]
Thank you very much, I was able to finally configure everything and it worked like a charm! I'm using 2 Yii installations behind a load balancer (using round robin, no sticky sessions). Before using your project I had issues with assets. Now it's working perfectly, thanks.

So, for those interested the steps I have performed were:

```
1) Edit config/console.php

    'modules' => [
        'staticAssets' => [
            'class' => \SamIT\Yii2\StaticAssets\Module::class,
            'excludedPatterns' => [
                '*/tests/*',
                '*/vendor/aws/*',
                [... etc ...]
                '*/vendor/yiisoft/yii2-httpclient*',
            ]
        ],
    ],

2) mkdir web/assets/build-1

3) ./yii staticAssets/asset/publish web/assets/build-1

4) Edit config/web.php

    'components' => [
        'assetManager' => [
            'class' => \SamIT\Yii2\StaticAssets\ReadOnlyAssetManager::class,
            'assetDevelopmentMode' => false,
            'baseUrl' => '@web/assets/build-1',
        ],
    ],
 ```
And that's all. Thanks!
